FROM debian:bullseye
#debian 11 bullseye

LABEL org.opencontainers.image.authors="another.mfj@yandex.ru"
LABEL org.opencontainers.image.title="php-7.4"
LABEL org.opencontainers.image.description="Image for development"
LABEL org.opencontainers.image.url="https://hub.docker.com/r/lmrctt/php"
LABEL org.opencontainers.image.source="https://github.com/another-ghu/docker/tree/main/unit/php-7.4"
LABEL org.opencontainers.image.documentation="https://github.com/another-ghu/docker/tree/main/unit/php-7.4"

RUN <<Packages
# add repositories and install pkg
apt update && apt install -y unzip curl apt-transport-https gnupg2 lsb-release

curl -o /usr/share/keyrings/nginx-keyring.gpg     \
    https://unit.nginx.org/keys/nginx-keyring.gpg

echo "deb [signed-by=/usr/share/keyrings/nginx-keyring.gpg]         \
    https://packages.nginx.org/unit/debian/ `lsb_release -cs` unit" \
    >> /etc/apt/sources.list.d/unit.list
echo "deb-src [signed-by=/usr/share/keyrings/nginx-keyring.gpg]     \
    https://packages.nginx.org/unit/debian/ `lsb_release -cs` unit" \
    >> /etc/apt/sources.list.d/unit.list
echo "deb http://deb.debian.org/debian/ `lsb_release -cs` main"     \
    >> /etc/apt/sources.list

apt update && apt install -y            \
    php7.4-common                       \
    php7.4-cli                          \
    php7.4-pgsql                        \
    php7.4-zip                          \
    php7.4-gd                           \
    php7.4-uuid                         \
    php7.4-mbstring                     \
    libphp7.4-embed                     \
    php7.4-dev                          \
    php7.4-curl                         \
    unit                                \
    unit-php

pecl channel-update pecl.php.net
pecl install xdebug-3.1.0

apt remove -y           \
    apt-transport-https \
    gnupg2              \
    lsb-release         \
    php7.4-dev

apt autoremove --purge -y

rm -rf /var/lib/apt/lists/* /etc/apt/sources.list.d/*.list
Packages

COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer
COPY docker-entrypoint.sh /tmp

RUN <<Configurations
# creating configuration files
mkdir /docker-entrypoint.d/
cat << 'unit.json' > /docker-entrypoint.d/unit.json
{
    "listeners":
    {
        "*:80":
        {
            "pass": "routes"
        },
        "*:443":
        {
            "pass": "routes"
        },
    },

    "routes":
    [
        {
            "match":
            {
                "uri": "~\\.(css|gif|ico|jpg|js(on)?|png|svg|ttf|woff2?)$"
            },
            "action":
            {
                "share": "/www$uri"
            },
        },
        {
            "action":
            {
                "pass": "applications/app"

            },
        },
    ],
    "applications": {
        "app": {
            "type": "php",
            "root": "/www/",
            "index": "index.php",
        }
    }
}
unit.json

mkdir /www/
cat << 'index.php' > /www/index.php
<?php
phpinfo();
index.php

chmod -R 777 /www

echo "zend_extension = xdebug" >> /etc/php/7.4/embed/php.ini
cat << '99-xdebug.ini' > /etc/php/7.4/embed/conf.d/99-xdebug.ini
xdebug.mode=develop, debug
xdebug.start_with_request=yes
xdebug.discover_client_host=0
xdebug.client_host=host.docker.internal
99-xdebug.ini

mv /tmp/docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
chmod ugo+x /usr/local/bin/docker-entrypoint.sh

#Перенаправление вывода
ln -sf /dev/stderr /var/log/unit.log
Configurations

STOPSIGNAL SIGTERM
#Устанавливаем рабочую директорию
WORKDIR /www
# Пробрасываем порт в контейнер
EXPOSE 80
# Запускаем docker-entrypoint.sh при старте контейнера
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
# Запускаем nginx unit в нормальном режиме
CMD ["unitd", "--no-daemon", "--control", "unix:/var/run/control.unit.sock"]
# Запускаем nginx unit в debug режиме
#CMD ["unitd-debug","--no-daemon","--control","unix:/var/run/control.unit.sock"]
